name: CI

on:
  push:
    tags:
    - "v*"

jobs:
  test:
    name: Test release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15.5"

      - name: Run tests
        run: go test ./test

  build:
    name: Build all releases
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15.5"

      - uses: equinox-io/setup-release-tool@v1
        name: Install Equinox
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build for Linux (amd64)
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          GOOS: linux
          GOARCH: amd64
        run: go build -o ./qc-linux-amd64 -ldflags="-X github.com/simse/qc/cmd.Version=${VERSION}" main.go


      - name: Build for macOS (amd64)
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          GOOS: darwin
          GOARCH: amd64
        run: go build -o ./qc-darwin-amd64 -ldflags="-X github.com/simse/qc/cmd.Version=${VERSION}" main.go

      - name: Build for Windows (amd64)
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          GOOS: windows
          GOARCH: amd64
        run: go build -o ./qc-windows-amd64.exe -ldflags="-X github.com/simse/qc/cmd.Version=${VERSION}" main.go

      - name: Write Private Key to file
        run: echo "${{ secrets.EQUINOX_SIGNING_KEY }}" >> ./equinox.key

      - name: Release to Equinox
        run: equinox release --version="${{ steps.get_version.outputs.VERSION }}" --platforms="darwin_amd64 linux_amd64 windows_amd64" --signing-key=equinox.key --app="${{ secrets.EQUINOX_APP }}" --token="${{ secrets.EQUINOX_SECRET }}" github.com/simse/qc

      - name: Release to Github
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            qc-linux-amd64
            qc-darwin-amd64
            qc-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}