name: CI

on: push

jobs:
  test_source_code:
    name: Test source code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15.5"

      - name: Run tests
        run: go test ./test

  build:
    name: Build binary
    runs-on: ubuntu-20.04
    needs: test_source_code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15.5"

      #- uses: equinox-io/setup-release-tool@v1
      #  name: Install Equinox
      #  env:
      #    ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build for all platforms
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: bash scripts/cross_compile.sh

      - uses: actions/upload-artifact@v2
        with:
          name: qc
          path: build/

  # test_binary:
  #   name: Test binary
  #   runs-on: ubuntu-20.04
      

  release:
    name: Release qc
    runs-on: ubuntu-20.04
    needs: build
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: equinox-io/setup-release-tool@v1
        name: Install Equinox
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - uses: actions/download-artifact@v2
        name: Download build artifact
        with:
          name: qc
          path: build/
      
      - name: Write Equinox key
        run: echo "${{ secrets.EQUINOX_SIGNING_KEY }}" >> ./equinox.key

      - name: Release to Equinox
        run: equinox release --version="${{ steps.get_version.outputs.VERSION }}" --platforms="darwin_amd64 linux_amd64 windows_amd64" --signing-key=equinox.key --app="${{ secrets.EQUINOX_APP }}" --token="${{ secrets.EQUINOX_SECRET }}" -- -ldflags "-X github.com/simse/qc/cmd.Version=${{ steps.get_version.outputs.VERSION }}" github.com/simse/qc

      - name: Release to Github
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          files: |
            build/qc-linux-amd64
            build/qc-darwin-amd64
            build/qc-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}