name: Update Homebrew Formula

on:
  release:
    types: [released]

jobs:
  homebrew-release:
    runs-on: macOS-latest
    steps:
      - name: Release Homebrew Formula
        if: github.event.release.prerelease != true
        uses: garden-io/update-homebrew-action@v1
        with:
          packageName: 'qc'
          templatePath: 'qc-template.rb'
          tapRepo: 'simse/homebrew-tap'
          srcRepo: 'simse/qc'
          authToken: ${{ secrets.GITHUB_TOKEN }}